#+TITLE: Patrick Rehill site content
#+STARTUP: content

* Page Not Found
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/404.md
:TITLE: Page Not Found
:PERMALINK: /404.html
:SITEMAP: false
:END:

#+BEGIN_EXPORT jekyll
Sorry, but the page you were trying to view does not exist.
#+END_EXPORT

* About
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/about.md
:TITLE: About
:PERMALINK: /
:AUTHOR_PROFILE: true
:REDIRECT_FROM: /about/, /about.html
:INCLUDE: files
:END:

I am a postdoctoral research fellow at the RMIT Department of Economics, Finance, and Marketing. I focus on policy evaluation and applied econometrics work on large, linked administrative datasets like the ABS's [[https://orgmode.org/guide/Hyperlinks.html][PLIDA]]. I am also very interested in machine learning methods to estimate heterogeneous treatment effects particularly the causal forest. In particular I am interested in ways to extract insights from a causal forest, and ways to use the method in quasi-experimental research designs.

Prior to my current role I worked at the Australian Treasury, Australian National University, and as a consultant doing quantitative research work.

My recent paper in the International Statistical Review called [[https://onlinelibrary.wiley.com/doi/full/10.1111/insr.12610][How Do Applied Researchers Use the Causal Forest? A Methodological Review]] includes a [[files/causal_forest_papers.csv][web appendix detailing the 133 papers identified]].

* Archive Layout with Content
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/archive-layout-with-content.md
:LAYOUT: archive
:TITLE: Archive Layout with Content
:PERMALINK: /archive-layout-with-content/
:END:

#+BEGIN_EXPORT jekyll
A variety of common markup showing how the theme styles them.

# Header one

## Header two

### Header three

#### Header four

##### Header five

###### Header six

## Blockquotes

Single line blockquote:

> Quotes are cool.

## Tables

| Entry            | Item   |                                                              |
| --------         | ------ | ------------------------------------------------------------ |
| [John Doe](#)    | 2016   | Description of the item in the list                          |
| [Jane Doe](#)    | 2019   | Description of the item in the list                          |
| [Doe Doe](#)     | 2022   | Description of the item in the list                          |

| Header1 | Header2 | Header3 |
|:--------|:-------:|--------:|
| cell1   | cell2   | cell3   |
| cell4   | cell5   | cell6   |
|-----------------------------|
| cell1   | cell2   | cell3   |
| cell4   | cell5   | cell6   |
|=============================|
| Foot1   | Foot2   | Foot3   |

## Definition Lists

Definition List Title
:   Definition list division.

Startup
:   A startup company or startup is a company or temporary organization designed to search for a repeatable and scalable business model.

#dowork
:   Coined by Rob Dyrdek and his personal body guard Christopher "Big Black" Boykins, "Do Work" works as a self motivator, to motivating your friends.

Do It Live
:   I'll let Bill O'Reilly [explain](https://www.youtube.com/watch?v=O_HyZ5aW76c "We'll Do It Live") this one.

## Unordered Lists (Nested)

  * List item one 
      * List item one 
          * List item one
          * List item two
          * List item three
          * List item four
      * List item two
      * List item three
      * List item four
  * List item two
  * List item three
  * List item four

## Ordered List (Nested)

  1. List item one 
      1. List item one 
          1. List item one
          2. List item two
          3. List item three
          4. List item four
      2. List item two
      3. List item three
      4. List item four
  2. List item two
  3. List item three
  4. List item four

## Buttons

Make any link standout more when applying the `.btn` class.

## Notices

**Watch out!** You can also add notices by appending `{: .notice}` to a paragraph.
{: .notice}

## HTML Tags

### Address Tag

<address>
  1 Infinite Loop<br /> Cupertino, CA 95014<br /> United States
</address>

### Anchor Tag (aka. Link)

This is an example of a [link](http://github.com "Github").

### Abbreviation Tag

The abbreviation CSS stands for "Cascading Style Sheets".

*[CSS]: Cascading Style Sheets

### Cite Tag

"Code is poetry." ---<cite>Automattic</cite>

### Code Tag

You will learn later on in these tests that `word-wrap: break-word;` will be your best friend.

### Strike Tag

This tag will let you <strike>strikeout text</strike>.

### Emphasize Tag

The emphasize tag should _italicize_ text.

### Insert Tag

This tag should denote <ins>inserted</ins> text.

### Keyboard Tag

This scarcely known tag emulates <kbd>keyboard text</kbd>, which is usually styled like the `<code>` tag.

### Preformatted Tag

This tag styles large blocks of code.

<pre>
.post-title {
  margin: 0 0 5px;
  font-weight: bold;
  font-size: 38px;
  line-height: 1.2;
  and here's a line of some really, really, really, really long text, just to see how the PRE tag handles it and to find out how it overflows;
}
</pre>

### Quote Tag

<q>Developers, developers, developers&#8230;</q> &#8211;Steve Ballmer

### Strong Tag

This tag shows **bold text**.

### Subscript Tag

Getting our science styling on with H<sub>2</sub>O, which should push the "2" down.

### Superscript Tag

Still sticking with science and Isaac Newton's E = MC<sup>2</sup>, which should lift the 2 up.

### Variable Tag

This allows you to denote <var>variables</var>.

{% include base_path %}
{% for post in site.pages %}
{% include archive-single.html %}
{% endfor %}
#+END_EXPORT

* Posts by Category
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/category-archive.html
:LAYOUT: archive
:TITLE: Posts by Category
:PERMALINK: /categories/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}
{% include group-by-array collection=site.posts field="categories" %}

{% for category in group_names %}
  {% assign posts = group_items[forloop.index0] %}
  <h2 id="{{ category | slugify }}" class="archive__subtitle">{{ category }}</h2>
  {% for post in posts %}
    {% include archive-single.html %}
  {% endfor %}
{% endfor %}
#+END_EXPORT

* Posts by Collection
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/collection-archive.html
:LAYOUT: archive
:TITLE: Posts by Collection
:PERMALINK: /collection-archive/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}
{% capture written_label %}'None'{% endcapture %}

{% for collection in site.collections %}
  {% unless collection.output == false or collection.label == "posts" %}
    {% capture label %}{{ collection.label }}{% endcapture %}
    {% if label != written_label %}
      <h2 id="{{ label | slugify }}" class="archive__subtitle">{{ label }}</h2>
      {% capture written_label %}{{ label }}{% endcapture %}
    {% endif %}
  {% endunless %}
  {% for post in collection.docs %}
    {% unless collection.output == false or collection.label == "posts" %}
      {% include archive-single.html %}
    {% endunless %}
  {% endfor %}
{% endfor %}
#+END_EXPORT

* CV
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/cv.md
:LAYOUT: archive
:TITLE: CV
:PERMALINK: /cv/
:AUTHOR_PROFILE: true
:REDIRECT_FROM: /resume
:END:

#+BEGIN_EXPORT liquid
{% include base_path %}
#+END_EXPORT

** Education
- Ph.D (quantitative social science), POLIS, Australian National University, 2025
- Master of Public Policy and Management, University of Melbourne, 2018
- B.A. (Hons) in Politics and International Studies, University of Melbourne, 2015

** Research experience
- 2026 - Present: Postdoctoral Research Fellow
- 2025 : Research Assistant
  - _RMIT_
  - Conducting research on innovative causal inference methods and large, linked administrative data.
- 2024 - Present: Evaluation Analyst
  - _Australian Treasury_
  - Conducting evaluations of government programs, including the Medicare Levy Surcharge / Private Health Insurance Rebate and the Superannuation Work Test. Analyzing large, linked administrative datasets. Part-time seconded to the Australian Government's AI CoLab.
- 2021 - Present: Research Officer
  - _Australian National University_
  - Conducting quantitative social policy research with large administrative datasets.
- 2019 - 2023: Quantitative Research Consultant
  - _Independent Consultant_
  - Conducting quantitative research for not-for-profits. Clients include UNICEF, the International Womens Development Agency, Australian Environmental Grantmakers Network, and Australian Research Alliance for Children and Youth.
- 2018 - 2020: Research Officer
  - _Australian Environmental Grantmakers Network_
  - Conducted philanthropic ecosystem mapping, including authoring the yearly Giving Trends report and a joint report with the Department of Environment and Energy.
- 2017 - 2018: Research Analyst
  - _dandolopartners_
  - Graduate at a public policy focused management consulting firm.

** Teaching experience
- 2023, 2024: Sessional Academic
  - _Australian National University_
  - Co-convening SOCR8204 (Causal Inference) for Master of Applied Data Analytics students, focusing on experimental, quasi-experimental, and causal machine learning methods in R and Stata.
- 2018 - 2019: Teaching Associate
  - _University of Melbourne_
  - Tutored MULT30018 (Applied Research Methods), teaching quantitative research methods and SPSS to undergraduate social science students.
  
** [[https://pbrehill.github.io/publications/][Publications]]

#+BEGIN_EXPORT jekyll
[//]: # (Skills)

[//]: # (======)

[//]: # (* Statistical programming)

[//]: # (  * R)

[//]: # (  * Python)

[//]: # (  * SPSS)

[//]: # (* Skill 2)

[//]: # (  * Sub-skill 2.1)

[//]: # (  * Sub-skill 2.2)

[//]: # (  * Sub-skill 2.3)

[//]: # (* Skill 3)
  
[//]: # (Talks)

[//]: # (======)

[//]: # (  <ul>{% for post in site.talks reversed %})

[//]: # (    {% include archive-single-talk-cv.html  %})

[//]: # (  {% endfor %}</ul>)
  
[//]: # (Teaching)

[//]: # (======)

[//]: # (  <ul>{% for post in site.teaching reversed %})

[//]: # (    {% include archive-single-cv.html %})

[//]: # (  {% endfor %}</ul>)
#+END_EXPORT

* Markdown
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/markdown.md
:TITLE: Markdown
:PERMALINK: /markdown/
:AUTHOR_PROFILE: true
:REDIRECT_FROM: /md/, /markdown.html
:END:

#+BEGIN_EXPORT jekyll
## Locations of key files/directories

* Basic config options: _config.yml
* Top navigation bar config: _data/navigation.yml
* Single pages: _pages/
* Collections of pages are .md or .html files in:
  * _publications/
  * _portfolio/
  * _posts/
  * _teaching/
  * _talks/
* Footer: _includes/footer.html
* Static files (like PDFs): /files/
* Profile image (can set in _config.yml): images/profile.png

## Tips and hints

* Name a file ".md" to have it render in markdown, name it ".html" to render in HTML.
* Go to the [commit list](https://github.com/academicpages/academicpages.github.io/commits/master) (on your repo) to find the last version Github built with Jekyll. 
  * Green check: successful build
  * Orange circle: building
  * Red X: error
  * No icon: not built
* Academic Pages uses [Jekyll Kramdown](https://jekyllrb.com/docs/configuration/markdown/), GitHub Flavored Markdown (GFM) parser, which is similar to the version of Markdown used on GitHub, but may have some minor differences. 
  * Some of emoji supported on GitHub should be supposed via the [Jemoji](https://github.com/jekyll/jemoji) plugin :computer:.
  * The best list of the supported emoji can be found in the [Emojis for Jekyll via Jemoji](https://www.fabriziomusacchio.com/blog/2021-08-16-emojis_for_Jekyll/#computer) blog post.

## Resources
 * [Liquid syntax guide](https://shopify.github.io/liquid/tags/control-flow/)
 * [MathJax Documentation](https://docs.mathjax.org/en/latest/)

## MathJax 

Support for MathJax Version 3.0 is included in the template:

$$
\displaylines{
\nabla \cdot E= \frac{\rho}{\epsilon_0} \\\
\nabla \cdot B=0 \\\
\nabla \times E= -\partial_tB \\\
\nabla \times B  = \mu_0 \left(J + \varepsilon_0 \partial_t E \right)
}
$$

The default delimiters of `$$...$$` and `\\[...\\]` are supported for displayed mathematics, while `\\(...\\)` should be used for in-line mathematics (ex., \\(a^2 + b^2 = c^2\\))

**Note** that since Academic Pages uses Markdown which cases some interference with MathJax and LaTeX for escaping characters and new lines, although [some workarounds exist](https://math.codidact.com/posts/278763/278772#answer-278772).

## Markdown guide

Academic Pages uses [kramdown](https://kramdown.gettalong.org/index.html) for Markdown rendering, which has some differences from other Markdown implementations such as GitHub's. In addition to this guide, please see the [kramdown Syntax page](https://kramdown.gettalong.org/syntax.html) for full documentation.  

### Header three

#### Header four

##### Header five

###### Header six

## Blockquotes

Single line blockquote:

> Quotes are cool.

## Tables

### Table 1

| Entry            | Item   |                                                              |
| --------         | ------ | ------------------------------------------------------------ |
| [John Doe](#)    | 2016   | Description of the item in the list                          |
| [Jane Doe](#)    | 2019   | Description of the item in the list                          |
| [Doe Doe](#)     | 2022   | Description of the item in the list                          |

### Table 2

| Header1 | Header2 | Header3 |
|:--------|:-------:|--------:|
| cell1   | cell2   | cell3   |
| cell4   | ce
ll5   | cell6   |
|-----------------------------|
| cell1   | cell2   | cell3   |
| cell4   | cell5   | cell6   |
|=============================|
| Foot1   | Foot2   | Foot3   |

## Definition Lists

Definition List Title
:   Definition list division.

Startup
:   A startup company or startup is a company or temporary organization designed to search for a repeatable and scalable business model.

#dowork
:   Coined by Rob Dyrdek and his personal body guard Christopher "Big Black" Boykins, "Do Work" works as a self motivator, to motivating your friends.

Do It Live
:   I'll let Bill O'Reilly [explain](https://www.youtube.com/watch?v=O_HyZ5aW76c "We'll Do It Live") this one.

## Unordered Lists (Nested)

  * List item one 
      * List item one 
          * List item one
          * List item two
          * List item three
          * List item four
      * List item two
      * List item three
      * List item four
  * List item two
  * List item three
  * List item four

## Ordered List (Nested)

  1. List item one 
      1. List item one 
          1. List item one
          2. List item two
          3. List item three
          4. List item four
      2. List item two
      3. List item three
      4. List item four
  2. List item two
  3. List item three
  4. List item four

## Buttons

Make any link standout more when applying the `.btn` class.

## Notices

Basic notices or call-outs are supported using the following syntax:

```markdown
**Watch out!** You can also add notices by appending `{: .notice}` to the line following paragraph.
{: .notice}
```

which wil render as:

**Watch out!** You can also add notices by appending `{: .notice}` to the line following paragraph.
{: .notice}

### Footnotes

Footnotes can be useful for clarifying points in the text, or citing information.[^1] Markdown support numeric footnotes, as well as text as long as the values are unique.[^note]

```markdown
This is the regular text.[^1] This is more regular text.[^note]

[^1]: This is the footnote itself.
[^note]: This is another footnote.
```

[^1]: Such as this footnote.
[^note]: When using text for footnotes markers, no spaces are permitted in the name.

## HTML Tags

### Address Tag

<address>
  1 Infinite Loop<br /> Cupertino, CA 95014<br /> United States
</address>

### Anchor Tag (aka. Link)

This is an example of a [link](http://github.com "Github").

### Abbreviation Tag

The abbreviation CSS stands for "Cascading Style Sheets".

*[CSS]: Cascading Style Sheets

### Cite Tag

"Code is poetry." ---<cite>Automattic</cite>

### Code Tag

You will learn later on in these tests that `word-wrap: break-word;` will be your best friend.

You can also write larger blocks of code with syntax highlighting supported for some languages, such as Python:

```python
print('Hello World!')
```

or R:

```R
print("Hello World!", quote = FALSE)
```

### Details Tag (collapsible sections)

The HTML `<details>` tag works well with Markdown and allows you to include collapsible sections, see [W3Schools](https://www.w3schools.com/tags/tag_details.asp) for more information on how to use the tag.

<details>
  <summary>Collapsed by default</summary>
  This section was collapsed by default!
</details>

The source code:

```HTML
<details>
  <summary>Collapsed by default</summary>
  This section was collapsed by default!
</details>
```

Or, you can leave a section open by default by including the `open` attribute in the tag:

<details open>
  <summary>Open by default</summary>
  This section is open by default thanks to open in the &lt;details open&gt; tag!
</details>


### Emphasize Tag

The emphasize tag should _italicize_ text.

### Insert Tag

This tag should denote <ins>inserted</ins> text.

### Keyboard Tag

This scarcely known tag emulates <kbd>keyboard text</kbd>, which is usually styled like the `<code>` tag.

### Preformatted Tag

This tag styles large blocks of code.

<pre>
.post-title {
  margin: 0 0 5px;
  font-weight: bold;
  font-size: 38px;
  line-height: 1.2;
  and here's a line of some really, really, really, really long text, just to see how the PRE tag handles it and to find out how it overflows;
}
</pre>

### Quote Tag

<q>Developers, developers, developers&#8230;</q> &#8211;Steve Ballmer

### Strike Tag

This tag will let you <strike>strikeout text</strike>.

### Strong Tag

This tag shows **bold text**.

### Subscript Tag

Getting our science styling on with H<sub>2</sub>O, which should push the "2" down.

### Superscript Tag

Still sticking with science and Isaac Newton's E = MC<sup>2</sup>, which should lift the 2 up.

### Variable Tag

This allows you to denote <var>variables</var>.

***
**Footnotes**

The footnotes in the page will be returned following this line, return to the section on <a href="#footnotes">Markdown Footnotes</a>.
#+END_EXPORT

* Page not in menu
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/non-menu-page.md
:TITLE: Page not in menu
:PERMALINK: /non-menu-page/
:AUTHOR_PROFILE: true
:REDIRECT_FROM: /nmp/, /nmp.html
:END:

#+BEGIN_EXPORT jekyll
This is a page not in the menu. You can use markdown in this page.

Heading 1
======

Heading 2
======
#+END_EXPORT

* Page Archive
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/page-archive.html
:LAYOUT: archive
:TITLE: Page Archive
:PERMALINK: /page-archive/
:AUTHOR_PROFILE: false
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}
{% for post in site.pages %}
  {% include archive-single.html %}
{% endfor %}
#+END_EXPORT

* Portfolio
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/portfolio.html
:LAYOUT: archive
:TITLE: Portfolio
:PERMALINK: /portfolio/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}


{% for post in site.portfolio %}
  {% include archive-single.html %}
{% endfor %}
#+END_EXPORT

* Publications
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/publications.html
:LAYOUT: archive
:TITLE: Publications
:PERMALINK: /publications/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% if site.author.googlescholar %}
  <div class="wordwrap">You can also find my articles on
    <a href="{{ site.author.googlescholar }}">my Google Scholar profile</a>.
  </div>
{% endif %}

{% include base_path %}

{%- comment -%}
  Renders from _bibliography/papers.bib using jekyll-scholar.
  One long page, grouped by BibTeX entry type.
{%- endcomment -%}

{% assign groups = "article:Journal articles|unpublished:Preprints|techreport:Reports|misc:Other" | split: "|" %}

{% for g in groups %}
  {% assign pair = g | split: ":" %}
  {% assign bibtype = pair[0] | strip %}
  {% assign label   = pair[1] | strip %}
  {% assign q = '@' | append: bibtype %}

  {%- capture results -%}
    {% bibliography --file papers --query {{ q }} --template bib_item %}
  {%- endcapture -%}
  {% assign results = results | strip %}

  {% if results != "" %}
    <h2 id="{{ bibtype }}">{{ label }}</h2><hr />
    <ul class="publist">
      {{ results }}
    </ul>
  {% endif %}
{% endfor %}
#+END_EXPORT

* Sitemap
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/sitemap.md
:LAYOUT: archive
:TITLE: Sitemap
:PERMALINK: /sitemap/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}

A list of all the posts and pages found on the site. For you robots out there is an [XML version]({{ base_path }}/sitemap.xml) available for digesting as well.

<h2>Pages</h2>
{% for post in site.pages %}
  {% include archive-single.html %}
{% endfor %}

<h2>Posts</h2>
{% for post in site.posts %}
  {% include archive-single.html %}
{% endfor %}

{% capture written_label %}'None'{% endcapture %}

{% for collection in site.collections %}
{% unless collection.output == false or collection.label == "posts" %}
  {% capture label %}{{ collection.label }}{% endcapture %}
  {% if label != written_label %}
  <h2>{{ label }}</h2>
  {% capture written_label %}{{ label }}{% endcapture %}
  {% endif %}
{% endunless %}
{% for post in collection.docs %}
  {% unless collection.output == false or collection.label == "posts" %}
  {% include archive-single.html %}
  {% endunless %}
{% endfor %}
{% endfor %}
#+END_EXPORT

* Posts by Tags
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/tag-archive.html
:LAYOUT: archive
:TITLE: Posts by Tags
:PERMALINK: /tags/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}
{% include group-by-array collection=site.posts field="tags" %}

{% for tag in group_names %}
  {% assign posts = group_items[forloop.index0] %}
  <h2 id="{{ tag | slugify }}" class="archive__subtitle">{{ tag }}</h2>
  {% for post in posts %}
    {% include archive-single.html %}
  {% endfor %}
{% endfor %}
#+END_EXPORT

* Talk map
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/talkmap.html
:LAYOUT: archive
:TITLE: Talk map
:PERMALINK: /talkmap.html
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
<p>This map is generated from a Jupyter Notebook file in <a href="https://github.com/academicpages/academicpages.github.io/blob/master/_talks/talkmap.ipynb">/_talks/talkmap.ipynb</a>, which mines the location fields in the .md files in _talks/.</p>
<iframe src="/talkmap/map.html" height="700" width="850" style="border:none;"></iframe>
#+END_EXPORT

* Talks and presentations
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/talks.html
:LAYOUT: archive
:TITLE: Talks and presentations
:PERMALINK: /talks/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% if site.talkmap_link == true %}

<p style="text-decoration:underline;"><a href="/talkmap.html">See a map of all the places I've given a talk!</a></p>

{% endif %}

{% for post in site.talks reversed %}
  {% include archive-single-talk.html %}
{% endfor %}
#+END_EXPORT

* Teaching
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/teaching.html
:LAYOUT: archive
:TITLE: Teaching
:PERMALINK: /teaching/
:AUTHOR_PROFILE: true
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}

{% for post in site.teaching reversed %}
  {% include archive-single.html %}
{% endfor %}
#+END_EXPORT

* Terms and Privacy Policy
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/terms.md
:TITLE: Terms and Privacy Policy
:PERMALINK: /terms/
:MODIFIED: 2016-06-06
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}
{% include toc %}

## Privacy Policy

The privacy of my visitors is extremely important. This Privacy Policy outlines the types of personal information that is received and collected and how it is used.

First and foremost, I will never share your email address or any other personal information to anyone without your direct consent.

### Log Files

Like many other websites, this site uses log files to help learn about when, from where, and how often traffic flows to this site. The information in these log files include:

* Internet Protocol addresses (IP)
* Types of browser
* Internet Service Provider (ISP)
* Date and time stamp
* Referring and exit pages
* Number of clicks

All of this information is not linked to anything that is personally identifiable.

### Cookies and Web Beacons

When you visit this site "convenience" cookies are stored on your computer when you submit a comment to help you log in faster to [Disqus](http://disqus.com) the next time you leave a comment.

Third-party advertisers may also place and read cookies on your browser and/or use web beacons to collect information. This site has no access or control over these cookies. You should review the respective privacy policies on any and all third-party ad servers for more information regarding their practices and how to opt-out.

If you wish to disable cookies, you may do so through your web browser options. Instructions for doing so can be found on the specific web browsers' websites.

#### Google Analytics

Google Analytics is a web analytics tool I use to help understand how visitors engage with this website. It reports website trends using cookies and web beacons without identifying individual visitors. You can read [Google Analytics Privacy Policy](http://www.google.com/analytics/learn/privacy.html).
#+END_EXPORT

* Blog posts
:PROPERTIES:
:EXPORT_FILE_NAME: _pages/year-archive.html
:LAYOUT: archive
:TITLE: Blog posts
:PERMALINK: /year-archive/
:AUTHOR_PROFILE: true
:REDIRECT_FROM: /wordpress/blog-posts/
:END:

#+BEGIN_EXPORT jekyll
{% include base_path %}
{% capture written_year %}'None'{% endcapture %}
{% for post in site.posts %}
  {% capture year %}{{ post.date | date: '%Y' }}{% endcapture %}
  {% if year != written_year %}
    <h2 id="{{ year | slugify }}" class="archive__subtitle">{{ year }}</h2>
    {% capture written_year %}{{ year }}{% endcapture %}
  {% endif %}
  {% include archive-single.html %}
{% endfor %}
#+END_EXPORT
